# Generated by Django 4.1.3 on 2022-11-05 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_type",
            field=models.CharField(
                choices=[("Full Time", "Full Time"), ("Part Time", "Part Time")],
                default="",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
