# Generated by Django 4.1.3 on 2022-11-05 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0006_job_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="image",
            field=models.ImageField(default="", upload_to="jobs/"),
            preserve_default=False,
        ),
    ]
